language: ruby
sudo: true
rvm:
  - "2.2.3"
before_install:
  - sudo apt-get update -qq
install:
  - sudo make PUPPET="$(which puppet)" install
  - sudo ln --symbolic "$PWD" /vagrant
script: make GREP=/bin/grep SLEEP=/bin/sleep vm_shell='/bin/bash -c' vm_port=22 vm_user=travis test
