language: ruby
sudo: true
rvm:
  - "2.2.3"
before_install:
  - sudo apt-get update -qq
install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - export rvmsudo_secure_path=1
  - bundle install --jobs=3 --retry=3
  - rvmsudo bundle exec make PUPPET="$(which puppet)" install
  - sudo ln --symbolic "$PWD" /vagrant
script: make GREP=/bin/grep SLEEP=/bin/sleep vm_shell='ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no travis@127.0.0.1' vm_port=22 vm_user=travis test
