language: ruby
sudo: true
rvm:
  - "2.2.3"
install:
  - export rvmsudo_secure_path=1
  - bundle install --jobs=3 --retry=3
  - export PUPPET="${MY_RUBY_HOME}/bin/puppet"
  - rvmsudo bundle exec make install
script: make vm_shell=/bin/bash test
