include battery_indicator
include bittorrent
include browser
include calculator
include dvcs
include firewall
include flash
include fonts
include graph_visualizer
include image_editor
include image_viewer
include image_viewer_cli
include login_manager
include media_player
include ntpd
include password_manager
include photo_editor
include printing_system
include scanner
include screen_grabber
include screen_locker
include spell_checker
include sshd
include tor
include users
include vcard_validator
include window_manager
